name: geoimage
description: A geo-wrapper around the image project (https://pub.dev/packages/image)
version: 0.4.1+2
homepage: https://github.com/moovida/geoimage

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  path: ^1.8.3

  dart_jts: ^0.3.0+1

  # Apache 2.0
  image: ^4.5.4
    # git:
    #   url: https://github.com/brendan-duncan/image.git
    #   ref: 85b6b14521ceb9d25100cb34ab954d3eb98afdd2



dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.10
