name: geoimage
description: A geo-wrapper around the image project (https://pub.dev/packages/image)
version: 0.4.1
homepage: https://github.com/moovida/geoimage

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  path: ^1.8.3

  dart_jts: ^0.2.3

  # Apache 2.0
  image: 4.1.7 # stay stick until issue #680 is resolved


dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.17.10
